OPENAI_API_KEY = "sk-proj-yT7cKTqN7Oy68OicyzTlT3BlbkFJRlaI3SAfivj9cqgQhPsM"

[connections.postgresql]
driver = "postgresql"
server = "lzpostgresql.postgres.database.azure.com"
port = "5432"
database = "postgres"  
user_id = "lzadmin"  
password = "Kandhla44@"  
sslmode = "require"
connect_timeout = "10"
